name-template: BOSS Documentation $NEXT_PATCH_VERSION
tag-template: $NEXT_PATCH_VERSION

categories:
  - title: 📖 Theory
    label: 📖 Theory
  - title: 📖 Analysis
    label: 📖 Analysis
  - title: 📖 Software
    label: 📖 Software
  - title: 🔨 Internals
    labels:
      - ⚙️ Enhancement
      - ⚠️ Interface
      - ❗ Behavior
      - 🔨 Maintenance
      - 🖱️ DX

change-template: |
  <details>
  <summary>$TITLE (#$NUMBER)</summary>

  $BODY

  </details>

replacers:
  - search: /<summary>([a-z]+!?:\s*)(.*)</summary>/g
    replace: <summary>$2</summary>

sort-direction: ascending

template: |
  # Release $NEXT_PATCH_VERSION

  See all documentation [here](https://bes3.rtfd.io).

  $CHANGES
