tasks:
  - init: pyenv local 3.9
  - init: pip install -e .[dev]

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: true
    addComment: false
    addBadge: false
    addLabel: false

vscode:
  extensions:
    - charliermarsh.ruff
    - christian-kohler.path-intellisense
    - eamodio.gitlens
    - editorconfig.editorconfig
    - esbenp.prettier-vscode
    - executablebookproject.myst-highlight
    - github.vscode-github-actions
    - github.vscode-pull-request-github
    - ms-python.black-formatter
    - ms-python.python
    - ms-vscode.live-server
    - redhat.vscode-yaml
    - Soulcode.vscode-unwanted-extensions
    - stkb.rewrap
    - streetsidesoftware.code-spell-checker
    - tamasfe.even-better-toml
    - tyriar.sort-lines
    - yzhang.markdown-all-in-one
