version: 2

sphinx:
  builder: dirhtml
  configuration: docs/conf.py
  fail_on_warning: true

formats:
  - htmlzip

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    post_install:
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      - export PATH=/home/docs/.cargo/bin:$PATH
      - uv pip install --system -c .constraints/py3.9.txt -e .[doc]
