[build-system]
requires = [
    "setuptools>=36.2.1", # environment markers
    "setuptools_scm",
    "wheel",
]

[tool.setuptools_scm]
write_to = "version.py"

[tool.black]
exclude = '''
/(
    .*\.egg-info
    | .*build
    | \.eggs
    | \.git
    | \.pytest_cache
    | \.tox
    | \.venv
    | \.vscode
    | dist
)/
'''
include = '\.pyi?$'
preview = true
target-version = [
    'py310',
    'py311',
    'py36',
    'py37',
    'py38',
    'py39',
]

[tool.pyright]
exclude = [
    ".git",
    ".tox",
    "docs/_build",
]
include = [
    "docs/conf.py",
    "src",
    "tests",
]
reportGeneralTypeIssues = false
reportMissingParameterType = false
reportMissingTypeStubs = false
reportUnboundVariable = false
reportUnknownArgumentType = false
reportUnknownMemberType = false
reportUnknownParameterType = false
reportUnknownVariableType = false
reportUnusedClass = true
reportUnusedFunction = true
reportUnusedImport = true
reportUnusedVariable = true
typeCheckingMode = "strict"

[tool.ruff]
extend-exclude = ["typings"]
extend-select = [
    "A",
    "B",
    "BLE",
    "C4",
    "C90",
    "D",
    "EM",
    "ERA",
    "I",
    "ICN",
    "INP",
    "ISC",
    "N",
    "NPY",
    "PGH",
    "PIE",
    "PL",
    "Q",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "T20",
    "TCH",
    "TID",
    "TRY",
    "UP",
    "YTT",
]
ignore = [
    "D101",
    "D102",
    "D103",
    "D105",
    "D107",
    "D203",
    "D213",
    "D407",
    "D416",
    "E501",
    "SIM108",
]
show-fixes = true
target-version = "py37"
task-tags = ["cspell"]

[tool.ruff.per-file-ignores]
"docs/*" = [
    "E402",
    "INP001",
    "S101",
    "S113",
    "T201",
]
"docs/conf.py" = [
    "A00",
    "B006",
    "PLR0913",
]
"setup.py" = ["D100"]

[tool.ruff.pydocstyle]
convention = "google"
