---
title: Inclusive Monte Carlo samples
---

## Reconstructed $J/\psi$ samples

> [!WARNING]
> The path is still listed on the production page, but is no longer available.
> The latest $J/\psi$ samples have been reconstructed with **BOSS 6.6.4**. They are located here:

```bash
InclJpsi="/besfs3/offline/data/besfs2/offline/data/664-1/jpsi/"
```

<!-- prettier-ignore-start -->
| Year      | Round     | Inclusive **MC**  | Sub-folder                   |
| :-------------|:------|----------------:|:-----------------------------|
| 2009      | `round02` | $225 \times 10^6$ | `$InclJpsi/09mc/dst`
| 2012      | `round05` | $1.0 \times 10^9$ | `$InclJpsi/12mc/dst`
| 2017–2018 | `round11` | $0.3 \times 10^9$ | _hasn't been reconstructed yet_
| 2018–2019 | `round12` | $10 \times 10^9$  | _hasn't been reconstructed yet_
<!-- prettier-ignore-end -->

See an indication of the number of $J/\psi$ events in [this presentation](https://indico.ihep.ac.cn/event/8795/session/3/contribution/9/material/slides/0.pdf) (requires login).

The latest samples for BOSS version 7.0.8 according to the [production page (login required)](https://docbes3.ihep.ac.cn/~offlinesoftware/index.php/Data_production_with_version_V7.0.8#jpsi_data) are located here:

```bash
InclJpsi="/bes3fs/offline/data/708-1/jpsi/"
```

<!-- prettier-ignore-start -->
| Year | Round     |    Inclusive **MC** | Sub-folder                                       |
| :--- | :-------- | ------------------: | :----------------------------------------------- |
| 2009 | `round02` |   $224 \times 10^6$ | `/bes3fs/offline/data/708-1/jpsi/round02/mc/dst` |
| 2012 | `round05` | $1.087 \times 10^9$ | `/bes3fs/offline/data/708-1/jpsi/round05/mc/dst` |
| 2018 | `round11` |   $4.6 \times 10^9$ | `/bes3fs/offline/data/708-1/jpsi/round11/mc/dst` |
| 2019 | `round12` |   $4.1 \times 10^9$ | `/bes3fs/offline/data/708-1/jpsi/round12/mc/dst` |
<!-- prettier-ignore-end -->
