---
title: Troubleshooting
---

## I lost read-write access in my `afs` home folder {#read-write-access}

Read-write access to your `afs` home folder requires an _AFS access token_. Formerly, such a token could be obtained using the `klog` command. Since August 2019, this command has become: <!-- cspell:ignore aklog kinit klog -->

```bash
kinit $USER
aklog -d
```

You should now be able to read-write in _all_ your sessions.

:::{.callout-warning title="Why you keep losing the token"}
There are two common reasons why you do not have a token:

- **You logged in with an SSH key.** Since the IHEP permission update, logging in with an [SSH key](tips.qmd#ssh-keygen) no longer obtains an AFS token automatically, whereas logging in with your password does. You then have to run `kinit`&nbsp;/&nbsp;`aklog` by hand after each login.
- **The token expired.** Tokens are only valid for a limited period of time, so a long-running session loses read-write access even if you had a token when you logged in. Run the two commands again to renew it.

You can check whether you currently hold a token with:

```bash
tokens
```

:::

:::{.callout-important title="Without a token, `~/.bashrc` is not executed"}
The missing token does not only block you from writing in your home folder: files in your home folder cannot be _read_ either, so `~/.bash_profile` and `~/.bashrc` are not executed when you log in. Everything you set up there — in particular [the BOSS environment](/tutorials/getting-started/setup.qmd#step-8) — is then silently missing, which makes this look like a broken BOSS installation rather than an AFS problem.

If commands such as `boss.exe` are suddenly "not found" right after logging in, run `kinit $USER && aklog -d` first and then `source ~/.bashrc`.
:::

## I'm sure my job is set up correctly, but it keeps resulting this error

```default
JobOptionsSvc       ERROR # =======> <package>/share/jobOptions_<package>.txt
JobOptionsSvc       ERROR # (22,1): parse error
...
JobOptionsSvc       FATAL Job options errors.
ApplicationMgr      FATAL Error initializing JobOptionsSvc
```

Yep, this is a weird one... So far, the cause was usually that the `jobOptions_*.txt` ends in a comment. You can solve it by adding a new line to the file.

## I cannot run a bash script, but I'm sure it should work

It could be that you wrote the `.sh` script on Windows and the file wasn't stored with Linux line endings. You can change these line endings back to Linux using:

```bash
sed -i 's/\r$//' $fileName
```

## Some header files are not found when compiling my package

Check your `requirements` file. Packages that you need should be declared here as well. For instance, if you want to use `McTruth` packages such as `McParticle.h`, you should add the line:

```default
use McTruth     McTruth-*     Event
```

## I am not the right group for submitting jobs

If you receive the error message <!-- cspell:ignore mlgpu -->

```default
hep_sub: error: argument -g/--group: invalid choice: 'physics'
(choose from 'gpupwa', 'mlgpu')
```

or something with different group names, it means you are in the wrong job submit group. Write an email to Ms. Wen Shuoping to ask to be put in the group `physics` (or whatever group you need). <!-- cspell:ignore Shuoping -->

### No resources in job submit group

If you receive the error message

```default
No resources in your group(s). So the job can not be submitted.
```

you should ask to be put in a different group (probably `physics`). Write an email to Ms. Wen Shuoping.

## `ERROR: Failed to create new proc id` instead

Two known causes:

1. In the case of `hep_sub`, you should submit an **executable** bash script. Make the `sh` script executable using `chmod +x`. Use `boss.condor` in exactly the same way as `boss.exe`, that is, feed it a job options file (`txt`), not a bash script.
2. You sourced a bash script that contained an `export -f` statement (exporting a bash `function`). While this is correct way of exporting a function, it somehow affects BOSS. Change this statement into `export` (omit the `f` option) and the issue is fixed.

## I cannot try out `boss.exe` without jobs

It should be possible to run `boss.exe` without jobs (see [here](/tutorials/getting-started/setup.qmd#step-6)). Does it result in the following error message?

```default
boss.exe: error while loading shared libraries: libReflex.so:
cannot open shared object file: No such file or directory
```

If so, you probably forgot to [source TestRelease](/tutorials/getting-started/setup.qmd#step-5).

## I get a message about `sysInitialize()` when running a job

If you receive the following error message:

```default
**************************************************
              BOSS version: 7.0.4
************** BESIII Collaboration **************

the jobOptions file is: jobOptions_sim.txt
JobOptionsSvc       FATAL in sysInitialize(): standard std::exception is caught
JobOptionsSvc       ERROR locale::facet::_S_create_c_locale name not valid
ApplicationMgr      FATAL Error initializing JobOptionsS
```

it means the `LANG` environment variable has been set to a value that BOSS cannot handle. Set it to `C` instead by running:

```bash
export LANG=C
```

## I cannot use a graphical interface from `lxlogin`

If, for instance, you cannot view a `TBrowser` or cannot open the event display `besvis.exe`, but instead see <!-- cspell:ignore besvis -->

```default
In case you run from a remote ssh session, reconnect with ssh -Y
```

you probably logged in with an SSH key and even using `ssh -Y` won't help. If you really need the graphical interfaces from `lxlogin`, you will need to remove your public key from the `~/.ssh/authorized_keys` file (just open and edit, it's just a text file) and log in again.

## My analysis BOSS packages end in a segmentation fault

A common error is that you didn't book the `NTuple` or add the `NTuple::Item`s with `NTuple::Tuple::addItem`. This usually results in the following error.

<!-- cspell:ignore mccor -->

```default
...
DatabaseSvc: Connected to MySQL database
mccor = 0

 *** Break *** segmentation violation
    __boot()
    import sys, imp, os, os.path
```

## VS Code source control is stuck at `Scanning folder for git repositories`

Connect to the ihep server, press `Ctrl + Shift + P`and search for `Preferences: Open Settings`.
Search for the `Git: path` setting on the remote server. Verify that the path is set e.g. `"git.path": "/usr/bin/git"` in the JSON file.

## During the BOSS environment setup, a compatibility error occurs (e.g. with Python)

For BOSS version 7.0.8, you need to use `hep_container shell CentOS7`, otherwise you will encounter compatibility issues when trying to run the `cmt`or `boss.exe` commands. Depending on the version of BOSS you are using, you may need to use a different container (see [Accessing the server](/tutorials/getting-started/server.qmd#accessing-the-server)).
