# cspell:ignore unittests

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  documentation:
    name: Build documentation and run notebooks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          sudo apt-get -y install pandoc
      - name: Build documentation and run notebooks
        working-directory: docs
        env:
          EXECUTE_NB: YES
        run: make html
      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: html
          path: docs/_build/html

  style:
    name: Style checks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[sty]
      - name: Perform style checks
        run: pre-commit run -a
